name: "Feature Request"
description: "Suggest something new or improved"
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What do you want?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      default: 1
      options:
        - "Nice to have"
        - "Should have soon"
        - "Must have"
        - "Blocking other work"
